export const queryKeys = {
  getOneRoom: "getOneRoom",
  getOneUser: "getOneUser",
  getOneRole: "getOneRole",
  getAllRooms: "getAllRooms",
  getAllUsers: "getAllUsers",
  getAllRoles: "getAllRoles",
  getOneDevice: "getOneDevice",
  getAllBlinds: "getAllBlinds",
  getAllDevices: "getAllDevices",
  authorizeUser: "authorizeUser",
  getAllPermissions: "getAllPermissions",
  getAllThermometers: "getAllThermometers",
  getDeviceDataForGraph: "getDeviceDataForGraph",
  getOneSensorDataByDeviceId: "getOneSensorDataByDeviceId",
};
