name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old image version
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/smart-house-frontend:latest || true

      - name: Build Docker Image
        run: |
          docker build --build-arg VITE_API=${{ secrets.VITE_API }} -t ${{ secrets.DOCKER_USERNAME }}/smart-house-frontend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/smart-house-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/smart-house-frontend:latest
            docker stop smart-house-frontend || true
            docker rm smart-house-frontend || true
            docker run -d --name smart-house-frontend -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/smart-house-frontend:latest
